export const demoRequestList = [
    {
      requestCode: 4000,
      offerUserId: "12345678",
      date: "20/03/24",
      tohour: "12:00",
      userCodeOffers: null,
      profession: 2,
      addressProfession: "string",
      note: "string",
      cameThroughFriend: 1,
      city: "ירושלים",
      fromhour: "09:00",
      user: null,
      Calander: true,
      matchedName: "Avi",
      matchedPhon: "052715454",
      matchedEmail: "h@gmail.com"
    },
    {
      requestCode: 4000,
      offerUserId: "12345678",
      date: "20/03/24",
      tohour: "12:00",
      userCodeOffers: null,
      profession: 2,
      addressProfession: "string",
      note: "string",
      cameThroughFriend: 1,
      city: "ירושלים",
      fromhour: "09:00",
      user: null,
      Calander: false,
    }
  ];
